### ISSUE TITLE
Radio Group sample page in FluentUIServerSample app is broken

### ISSUE THREAD

**Issue by danroth27** [microsoft/fast-blazor#34]
Repro steps:

- Run the FluentUIServerSample
- Click on Web components
- Click on the Radio Group link

Error in the browser console:

```
blazor.server.js:21 [2021-05-06T05:40:30.692Z] Error: System.InvalidOperationException: Unable to set property 'required' on object of type 'Microsoft.Fast.Components.FluentUI.FluentRadioGroup'. The error was: Unable to cast object of type 'System.String' to type 'System.Nullable`1[System.Boolean]'.
 ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Nullable`1[System.Boolean]'.
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.Fast.Components.FluentUI.FluentInputBase`1.SetParametersAsync(ParameterView parameters) in C:\Users\daroth\Documents\GitHub\microsoft\fast-blazor\src\Microsoft.Fast.Components.FluentUI\FluentInputBase.cs:line 140
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by dpsthree** [comment]
https://github.com/microsoft/fast-blazor/pull/43 would close this.

**Comment by danroth27** [comment]
Looks like this is fixed now. @awentzel Close?

**Comment by EisenbergEffect** [comment]
Thanks @dpsthree !
