### ISSUE TITLE
Unable to set property 'orientation' on object of type Microsoft.Fast.Components.FluentUI.FluentTabs

### ISSUE THREAD

**Issue by danroth27** [microsoft/fast-blazor#36]
Repro steps:

- Run the FluentUIServerSample
- Select the web components
- Select the Tabs link

Error in the browser console:

```
[2021-05-06T05:49:01.699Z] Error: System.InvalidOperationException: Unable to set property 'orientation' on object of type 'Microsoft.Fast.Components.FluentUI.FluentTabs'. The error was: Unable to cast object of type 'System.String' to type 'System.Nullable`1[Microsoft.Fast.Components.FluentUI.Orientation]'.
 ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Nullable`1[Microsoft.Fast.Components.FluentUI.Orientation]'.
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by dpsthree** [comment]
https://github.com/microsoft/fast-blazor/pull/44 would close this.

**Comment by danroth27** [comment]
@awentzel Close?

**Comment by EisenbergEffect** [comment]
Thanks @dpsthree !
